<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="21299" started-at="2018-02-13T05:39:32Z" finished-at="2018-02-13T05:39:53Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="21299" started-at="2018-02-13T05:39:32Z" finished-at="2018-02-13T05:39:53Z">
      <class name="Tests.RegistrationPageTests">
        <test-method status="PASS" signature="startup()[pri:0, instance:Tests.RegistrationPageTests@343f4d3d]" name="startup" is-config="true" duration-ms="15689" started-at="2018-02-13T11:09:32Z" finished-at="2018-02-13T11:09:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startup -->
        <test-method status="PASS" signature="createRegObj()[pri:0, instance:Tests.RegistrationPageTests@343f4d3d]" name="createRegObj" is-config="true" duration-ms="19" started-at="2018-02-13T11:09:47Z" finished-at="2018-02-13T11:09:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createRegObj -->
        <test-method status="FAIL" signature="fillAndSubmitRegistrationForm()[pri:1, instance:Tests.RegistrationPageTests@343f4d3d]" name="fillAndSubmitRegistrationForm" duration-ms="5573" started-at="2018-02-13T11:09:47Z" finished-at="2018-02-13T11:09:53Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Cell index must be >= 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Cell index must be >= 0
	at org.apache.poi.xssf.usermodel.XSSFRow.getCell(XSSFRow.java:270)
	at org.apache.poi.xssf.usermodel.XSSFRow.getCell(XSSFRow.java:259)
	at BasePages.GenericActions.readTestData(GenericActions.java:40)
	at Demoqa.RegistrationPage.enterUserName(RegistrationPage.java:118)
	at Tests.RegistrationPageTests.fillAndSubmitRegistrationForm(RegistrationPageTests.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fillAndSubmitRegistrationForm -->
      </class> <!-- Tests.RegistrationPageTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
